version: '3.3'
services:
  back:
    build: 
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/:/data/
    tty: true
    command: uvicorn main:app --host=0.0.0.0 --port=8080
    container_name: back
